[package]
name = "sequencer"
version = "0.1.0"
authors = ["Espresso Systems <hello@espressosys.com>"]
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
testing = ["hotshot-testing"]

[dev-dependencies]
espresso-macros = { git = "https://github.com/EspressoSystems/espresso-macros.git", tag = "0.1.0" }
hotshot-query-service = { workspace = true, features = ["testing"] }
portpicker = "0.1.1"
rand = "0.8.5"
tempfile = "3.9.0"

[dependencies]
anyhow = { workspace = true }
ark-bls12-381 = { workspace = true }
ark-ec = { workspace = true }
ark-ed-on-bn254 = { workspace = true }
ark-ff = { workspace = true }
ark-serialize = { workspace = true, features = ["derive"] }
ark-std = { workspace = true }
async-compatibility-layer = { workspace = true }
async-std = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
bincode = "1.3.3"
bytesize = { workspace = true }
clap = { workspace = true }
cld = { workspace = true }
commit = { git = "https://github.com/EspressoSystems/commit" }
contract-bindings = { path = "../contract-bindings" }
derivative = "2.2"
derive_more = { workspace = true }
ethers = { workspace = true }
ethers-contract-derive = "2.0.10"
futures = { workspace = true }
tagged-base64 = { workspace = true }
zeroize = { workspace = true }

hotshot = { workspace = true }
hotshot-orchestrator = { workspace = true }
hotshot-query-service = { workspace = true }
hotshot-stake-table = { workspace = true }
hotshot-task = { workspace = true }

# Dependencies for feature `testing`
hotshot-testing = { workspace = true, optional = true }
hotshot-types = { workspace = true }
hotshot-web-server = { workspace = true }
include_dir = "0.7"
itertools = { workspace = true }
portpicker = "0.1.1" # TODO: optional?
tempfile = "3.9.0" # TODO: optional?

jf-primitives = { workspace = true }
jf-utils = { workspace = true } # TODO temporary: used only for test_rng()
lazy_static = "1.4"
num-traits = "0.2.18"
rand = "0.8.5"
rand_chacha = { workspace = true }
rand_distr = { workspace = true }
sequencer-utils = { path = "../utils" }
serde = { workspace = true }
serde_json = "^1.0.113"
sha2 = "0.10" # TODO temporary, used only for VID, should be set in hotshot
snafu = { workspace = true }
surf-disco = { workspace = true }
tide-disco = { workspace = true }
time = "0.3"
tokio-postgres = { version = "0.7", default-features = false, features = [ # disabling the default features removes dependence on the tokio runtime
    "with-serde_json-1",
] }
toml = { workspace = true }
tracing = { workspace = true }
trait-set = "0.3.0"
trait-variant = { workspace = true }
typenum = { version = "1.15.0", default-features = false, features = [
    "no_std",
] }
url = { workspace = true }
