[workspace.package]
version = "0.1.0"
authors = ["Espresso Systems <hello@espressosys.com>"]
edition = "2021"

[workspace]

resolver = "2"

members = [
  "contract-bindings",
  "contracts/rust/adapter",
  "contracts/rust/diff-test",
  "contracts/rust/gen-vk-contract",
  "hotshot-state-prover",
  "sequencer",
  "utils",
]

[workspace.dependencies]
anyhow = "^1.0"
ark-std = "0.4"
ark-bls12-381 = "0.4"
ark-bn254 = "0.4"
ark-ec = "0.4"
ark-ed-on-bn254 = "0.4"
ark-ff = "0.4"
ark-poly = "0.4"
ark-serialize = "0.4"
async-compatibility-layer = { git = "https://github.com/EspressoSystems/async-compatibility-layer", tag = "1.4.1", features = [
  "logging-utils",
] }
async-std = { version = "1.12.0", features = ["attributes", "tokio1"] }
async-trait = "0.1.77"
base64 = "0.22"
base64-bytes = "0.1"
clap = { version = "4.4", features = ["derive", "env", "string"] }
cld = "0.5"
derive_more = "0.99.17"
es-version = { git = "https://github.com/EspressoSystems/es-version.git", branch = "main" }
dotenvy = "0.15"
ethers = { version = "2.0", features = ["solc"] }
futures = "0.3"
hotshot = { git = "https://github.com/EspressoSystems/hotshot", tag = "0.5.28" }
hotshot-orchestrator = { git = "https://github.com/EspressoSystems/hotshot", tag = "0.5.28" }
hotshot-query-service = { git = "https://github.com/EspressoSystems/hotshot-query-service", branch = "abdul/fix-commit-parsing" }
hotshot-stake-table = { git = "https://github.com/EspressoSystems/hotshot", tag = "0.5.28" }
hotshot-state-prover = { version = "0.1.0", path = "hotshot-state-prover" }
hotshot-task = { git = "https://github.com/EspressoSystems/hotshot", tag = "0.5.28" }
hotshot-testing = { git = "https://github.com/EspressoSystems/hotshot", tag = "0.5.28" }
hotshot-types = { git = "https://github.com/EspressoSystems/hotshot", tag = "0.5.28" }
hotshot-web-server = { git = "https://github.com/EspressoSystems/hotshot", tag = "0.5.28" }
jf-plonk = { git = "https://github.com/EspressoSystems/jellyfish", tag = "0.4.2", features = [
  "test-apis",
  "test-srs",
] }
jf-primitives = { git = "https://github.com/EspressoSystems/jellyfish", tag = "0.4.2", features = [
  "std",
  "test-srs",
] }
jf-relation = { git = "https://github.com/EspressoSystems/jellyfish", tag = "0.4.2", features = [
  "std",
] }
jf-utils = { git = "https://github.com/EspressoSystems/jellyfish", tag = "0.4.2" }
snafu = "0.8"
strum = { version = "0.26", features = ["derive"] }
surf-disco = { git = "https://github.com/EspressoSystems/surf-disco", tag = "v0.5.0" }
tagged-base64 = { git = "https://github.com/EspressoSystems/tagged-base64", tag = "0.3.4" }
tide-disco = { git = "https://github.com/EspressoSystems/tide-disco", tag = "v0.5.0" }
tracing = "0.1"
trait-variant = "0.1"
bytesize = "1.3"
itertools = "0.12"
rand_chacha = "0.3"
rand_distr = "0.4"
serde = { version = "1.0.195", features = ["derive"] }
toml = "0.8"
url = "2.3"
versioned-binary-serialization = { git = "https://github.com/EspressoSystems/versioned-binary-serialization.git", tag = "0.1.2" }
zeroize = "1.7"
