[package]
name = "sequencer-utils"
version = "0.1.0"
authors = ["Espresso Systems <hello@espressosys.com>"]
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
ark-serialize = { version = "0.4", features = ["derive"] }
async-std = { workspace = true }
commit = { git = "https://github.com/EspressoSystems/commit" }
contract-bindings = { path = "../contract-bindings" }
ethers = "2.0.14"
portpicker = "0.1.1"
surf = "2.3.2"
tempfile = "3.9.0"
tracing = "0.1.37"
url = "2.3.1"
