# Fails if process-compose is edited but not docker-compose
name: Check Demo Consistency

on:
  pull_request:
    paths:
      - 'process-compose.yaml'
      - 'docker-compose.yaml'

jobs:
  check-edits:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with: 
          fetch-depth: 2
      
      - name: Check for file edits
        run: |
          git fetch origin main
          FILES_CHANGED=$(git diff --name-only origin/main..HEAD)

          # Check if process-compose.yaml is edited
          if echo "$FILES_CHANGED" | grep "process-compose.yaml"; then
            # Fail if docker-compose.yml is not also edited
            if ! echo "$FILES_CHANGED" | grep "docker-compose.yaml"; then
              echo "process-compose.yaml is edited but not docker-compose.yaml"
              echo "If this was intentional, you may ignore this failure"
              exit 1
            fi
          fi
